### ISSUE TITLE
[Bug] Delete button may remove multiple elements

### ISSUE THREAD

**Issue by Freymaurer** [Rookabu/Supermega-Projekt#4]
Step by Step:

- Refresh website
- Add one element "Test1"
- Refresh website
- Add one element "Test2"
- Delete "Test1"
- Deletes "Test1" and "Test2"

I would expect to only delete one element, when clicking on the "X" button.

**Comment by Rookabu** [comment]
Fixed it:
```
Html.td [
  Bulma.delete [
    delete.isMedium
    prop.onClick (fun _ ->                                            
    table |> List.removeAt i |> megaSet
    )
  ]
]
```
